# Generated by Django 4.0.4 on 2022-05-23 15:19

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='media/rango.jpg', upload_to=blog.models.upload_to, verbose_name='Image'),
        ),
    ]
