# Generated by Django 4.0.4 on 2022-05-23 15:21

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='rango.jpg', upload_to=blog.models.upload_to, verbose_name='Image'),
        ),
    ]
