# Generated by Django 4.0.4 on 2022-05-31 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_parent_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='distance_units',
            field=models.CharField(choices=[('kilometers', 'km'), ('miles', 'mi')], default='mi', max_length=10),
        ),
    ]
