# Generated by Django 4.0.4 on 2022-05-31 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_distance_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='activity_type',
            field=models.CharField(choices=[('Running', 'Running'), ('Biking', 'Biking'), ('Swimming', 'Swimming')], default='running', max_length=8),
        ),
        migrations.AlterField(
            model_name='post',
            name='distance_units',
            field=models.CharField(choices=[('km', 'Kilometers'), ('mi', 'Miles')], default='mi', max_length=10),
        ),
    ]
